name: notifications
description: Notificaions.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+3

environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  permission_handler: ^9.2.0
  onesignal_flutter: ^3.3.0
  flutter_local_notifications: ^9.4.0
  future_progress_dialog: ^0.1.1
  shared_preferences: ^2.0.13

dev_dependencies:

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

#  assets: