name: fluttergistshop
description: Gistshop.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  get: ^4.6.1
  flutter_screenutil: ^5.3.1
  ionicons: ^0.1.2
  http: ^0.13.4
  firebase_auth:
  cached_network_image: ^3.2.0
  image_picker:
  image_cropper: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300

  assets:
    - assets/images/